markdown: kramdown
highlighter: rouge
permalink: /posts/:title
rdiscount:
  extensions: [smart]

name: ratibus' blog
author: Eric Lemoine
url: http://blog.ratibus.net
description: Eric Lemoine's, aka ratibus, blog
twitter: ratibus
github: ratibus
gravatar_url: http://gravatar.com/avatar/4bb93034715732d444b300fc0bd5dfd6
linkedin: elemoine
