markdown: kramdown
pygments: true
permalink: /posts/:title
auto: true
rdiscount:
  extensions: [smart]

name: Eric Lemoine
url: http://blog.ratibus.net
description: A fantastic blog that is fantastic.
twitter: ratibus
github: ratibus
gravatar_url: http://gravatar.com/avatar/4bb93034715732d444b300fc0bd5dfd6
linkedin: elemoine