markdown: kramdown

kramdown:
  input: GFM
  hard_wrap: false

highlighter: rouge
permalink: /posts/:title
rdiscount:
  extensions: [smart]

name: ratibus' blog
author: Eric Lemoine
url: https://blog.ratibus.net
description: Eric Lemoine's, aka ratibus, blog
twitter: ratibus
github: ratibus
gravatar_url: https://gravatar.com/avatar/4bb93034715732d444b300fc0bd5dfd6
linkedin: elemoine
